# Generated by Django 3.1.6 on 2021-02-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_auto_20210222_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
