# Generated by Django 3.1.6 on 2021-02-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_auto_20210223_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='company_id',
            new_name='company',
        ),
    ]
