# Generated by Django 3.1.6 on 2021-02-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='company_id',
            new_name='company',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
