# Generated by Django 3.1.6 on 2021-03-03 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0006_auto_20210226_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-started']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='changed',
            new_name='finished',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='published',
            new_name='started',
        ),
        migrations.AddField(
            model_name='company',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='interaction_type',
            field=models.CharField(choices=[('a', 'application'), ('m', 'mail'), ('s', 'site'), ('i', 'initiative')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.company', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='email',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.company', verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.company', verbose_name='phone'),
        ),
    ]
