# Generated by Django 3.1.6 on 2021-03-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_remove_message_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CRM.project', verbose_name='project'),
            preserve_default=False,
        ),
    ]
