# Generated by Django 3.1.6 on 2021-03-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_message_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='project',
        ),
    ]
